# NumPy- numerical python
advantages of NumPy:

*   allows several mathematical operations   
*   faster operations



In [ ]:
#list and tuples are collections of values in int we can only store on value but in list
#it can be multiple they both are inbuilt data types of python

In [1]:
import numpy as np

list vs numpy - time taken


In [2]:
from time import process_time

In [3]:
#time taken by a list
python_list =[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()
print(end_time-start_time)#the difference will find the number of seconds in which the process will be completed

0.0011272590000004357


In [4]:
np_array=np.array([i for i in range(10000)])#time taken for numpy array to complete this process
start_time=process_time()
np_array=np_array+5 # or np_array+=5
end_time=process_time()
print(end_time-start_time)

0.001393621000000067


Numpy Arrays

In [5]:
#list
list1=[1,2,3,4,5]
print(list1)#in list elements are seperated by a comma
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array=np.array([1,2,3,4,5])
print(np_array) #in array the elements are not seperated by a comma
type(np_array) #the type nd represents n dimension array

[1 2 3 4 5]


numpy.ndarray

In [7]:
#creating one dimensional array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape #only one value i.e. 1d array and the 4 represents the number of columns

(4,)

In [9]:
#two d arrays
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape #row by column

(2, 4)

In [11]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float) #default value of data type is int

In [12]:
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays


In [16]:
# create a numpy array of zeroes
x=np.zeros((4,5),dtype =int ) #this will print an array of 4 rows and 5 columns
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [17]:
#create a numpy array of 1s
x=np.ones((4,5),dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
#create an array of particular value
z=np.full((4,4),7.8)
print(z)

[[7.8 7.8 7.8 7.8]
 [7.8 7.8 7.8 7.8]
 [7.8 7.8 7.8 7.8]
 [7.8 7.8 7.8 7.8]]


In [23]:
#create an identity matrix
a = np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [26]:
# create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.51996578 0.55708272 0.34852191 0.13923596]
 [0.58074877 0.8891267  0.11434402 0.19000954]
 [0.29335825 0.29197579 0.31293375 0.06747636]]


In [27]:
#random integer value arrays

In [29]:
c=np.random.randint(10,100,(3,4)) #prints a random int value within a specific range between 10 to 100
print(c)

[[17 99 67 71]
 [27 64 28 54]
 [32 52 54 60]]


In [31]:
#array or evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5,dtype=int)#this will give 5 values between 10 to 30 that is evenly spaced
print(d)

[10 15 20 25 30]


In [37]:
#arrays of evenly spaced values --> specifying the steps required
e =np.arange(10,30,5)#30 will not be included
print(e)

[10 15 20 25]


In [39]:
#convert a list to a numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [40]:
c=np.random.randint(10,90,(5,5))
print(c)

[[12 64 15 37 20]
 [66 23 75 56 39]
 [46 28 41 38 61]
 [64 61 48 12 45]
 [26 44 52 38 17]]


In [41]:
print(c.shape)

(5, 5)


In [42]:
#number of dimensions
print(c.ndim)

2


In [43]:
#number of elements in an array
c.size

25

In [45]:
print(c.dtype)

int64


mathematical operations on a numpy array


In [46]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)#concatenate

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 2 8]
 [6 3 3]
 [9 9 9]]
[[15 16 15]
 [12 15 17]
 [18 19 13]]


Incase of list if we use + sign it will join or concatenate the two lists but incase of a numpy array it will add the elements

In [48]:
print(a+b) #we can use np.add(a,b) function

[[22 18 23]
 [18 18 20]
 [27 28 22]]


In [49]:
print(a-b) #np.subtract(a,b)
print(a*b) #np.multiply(a,b)
print(a/b) #np.divide(a,b)

[[ -8 -14  -7]
 [ -6 -12 -14]
 [ -9 -10  -4]]
[[105  32 120]
 [ 72  45  51]
 [162 171 117]]
[[0.46666667 0.125      0.53333333]
 [0.5        0.2        0.17647059]
 [0.5        0.47368421 0.69230769]]


array manipulation


In [51]:
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 3 8]
 [7 6 8]]
(2, 3)


In [52]:
#transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[5 7]
 [3 6]
 [8 8]]
(3, 2)


In [53]:
# reshaping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 7 9]
 [1 7 6]]
(2, 3)


In [54]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 7]
 [9 1]
 [7 6]]
(3, 2)
